# https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source
arb-dir: assets/l10n
template-arb-file: intl_en.arb
output-dir: lib/generated/l10n
output-class: L10n
preferred-supported-locales: ["en"]
