name: Bug report
description: Create a report to help us improve
title: "[BUG] Quick description of the bug"
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Ensure that you have searched the [existing issues](https://github.com/linagora/twake-on-matrix/issues).
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    attributes:
        label: Pre-Bug State
        description: Describe the condition or state of the app immediately before the bug was encountered
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected results
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context
      description: Please provide as much detail as possible
      value: |
         - Device: [e.g. iPhone6]
         - OS: [e.g. iOS]
         - Browser: [e.g. chrome, safari]
         - App Version: [e.g. 22]
         - Server: [e.g. production, example.com]
         - Account information:
         - Others
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or Video
      description: |
        Upload any screenshots or video of the bug if applicable
      value: |
        <details open>
        <summary>Screenshots / Video demonstration</summary>

        [Upload media here]

        </details>
  - type: textarea
    attributes:
      label: Logs
      description: Provide any related logs if applicable
      value: |
        <details open><summary>Logs</summary>

        ```console
        [Paste your logs here]
        ```

        </details>
  - type: textarea
    attributes:
      label: Additional information
      description: Provide any additional information if applicable 
      value: |
         - Frequency
         - Others
    validations:
      required: false