# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_ci

default_platform(:mac)

platform :mac do
  desc "Sync development signing certificates"
  lane :sync_dev do
    sync_code_signing(
      type: "development",
      git_private_key: ENV["APPLE_CERTIFICATES_SSH_KEY"],
      skip_provisioning_profiles: true
    )
  end

  desc "Sync developer ID signing certificates"
  lane :sync_dev_id do
    sync_code_signing(
      type: "developer_id",
      git_private_key: ENV["APPLE_CERTIFICATES_SSH_KEY"],
      skip_provisioning_profiles: true
    )
  end

  desc "Notarizing the app"
  lane :notarization do
    app_store_connect_api_key(
      key_id: ENV["APPLE_KEY_ID"],
      issuer_id: ENV["APPLE_ISSUER_ID"],
      key_content: ENV["APPLE_KEY_CONTENT"]
    )
    notarize(
      package: "../twake-#{last_git_tag}-macos-amd64.dmg",
      bundle_id: "com.linagora.macos.twake",
      print_log: true,
      verbose: true
    )
  end
end
