import 'package:fluffychat/config/go_routes/app_routes.dart';
import 'package:go_router/go_router.dart';

/// The application's route list, generated by go_router_builder.
///
/// Use typed route classes (e.g. `const RoomsRoute().go(context)`) for
/// navigation instead of raw path strings.
final List<RouteBase> appRoutes = $appRoutes;
