/* Twake Chat — service worker: Web Push (RFC 8030) + precache.
 *
 * Pusher is event_id_only (same privacy contract as mobile): the push carries
 * NO message content — only event_id/room_id. The SW shows a generic
 * notification; the app fetches the content when the user clicks it. Sygnal's
 * events_only flag suppresses content-less count-clear pushes, so every push
 * maps to a real event (satisfies userVisibleOnly).
 *
 * A scope can only be controlled by a single service worker, so push and
 * precache share this file. Do not add a second registration under /web/: it
 * would silently replace this one.
 *
 * Precache manifest: generated by scripts/generate-sw-manifest.sh into
 * build/web/assets/sw-manifest.json. Flutter does not content-hash its output
 * filenames, so the manifest maps every scope-relative path to the MD5 of the
 * bytes that were actually deployed. The worker fetches it fresh at every boot
 * (nginx serves it with `Cache-Control: no-store`, and we also pass
 * {cache:'no-store'} so the browser HTTP cache can never hide a deploy) and
 * evicts exactly the entries whose hash changed. The worker itself is
 * version-independent: a deploy that only changes assets never reinstalls it.
 *
 * Since the manifest is fetched at runtime, this file is never built — keep it
 * as authored.
 *
 * ponytail: no JS test harness in this Flutter repo.
 */

'use strict';

// Reloaded from the network at the start of every boot. Sources of truth:
//   resources: { 'main.dart.js': 'md5', '/': '<index.html md5>', ... }
//   core:      ['main.dart.js', ...]  (subset of resources, precached eagerly)
// config.json, version.json and the manifest itself are deliberately absent:
// they are deploy-injected or carry the version, nginx serves them with
// 'Cache-Control: no-store', and we never intercept them.
const MANIFEST_URL = 'assets/sw-manifest.json';
const CACHE_NAME = 'twake-chat-cache';
const MANIFEST = 'twake-chat-manifest';

let manifest = { core: [], resources: {} };
let manifestLoaded = false;

// Keys in manifest.resources are scope-relative: the app is deployed under
// /web/, not at the origin root.
function resourceKey(url) {
  const scope = self.registration.scope;
  if (!url.startsWith(scope)) return null;
  const key = url.substring(scope.length);
  return key === '' ? '/' : key;
}

// Cachebuster for the SW's own asset fetches: appends the manifest MD5 as a
// GET param, so the URL is unique to the bytes actually deployed. A misbehaving
// middle layer that ignores `Cache-Control: no-cache` can never hand the fresh
// precache stale bytes pinned to the plain URL.
function withBust(url, hash) {
  const sep = url.includes('?') ? '&' : '?';
  return url + sep + 'v=' + hash;
}

function fetchManifest() {
  return fetch(MANIFEST_URL, { cache: 'no-store' })
    .then(function (response) {
      if (!response.ok) throw new Error('manifest HTTP ' + response.status);
      return response.json();
    })
    .then(function (data) {
      if (!data || typeof data.resources !== 'object' ||
          !Array.isArray(data.core)) {
        throw new Error('malformed manifest');
      }
      return data;
    });
}

function loadStoredManifest() {
  return caches.open(MANIFEST).then(function (cache) {
    return cache.match('manifest').then(function (response) {
      return response ? response.json() : null;
    });
  });
}

// Before activation completes, the fetch handler may run with an empty in-memory
// manifest. Load the stored one once so a reload right after a worker restart is
// still served from cache. Falls back to the network when there is nothing yet.
async function loadInitialManifest() {
  const stored = await loadStoredManifest();
  if (stored && stored.resources && Object.keys(stored.resources).length) {
    manifest = stored;
  }
  manifestLoaded = true;
  return manifest;
}

self.addEventListener('install', function (event) {
  self.skipWaiting();
  // Best-effort warm-up so the fetch handler can serve immediately after
  // activation. A failure here is fine: activation retries and both paths fall
  // back to the network.
  event.waitUntil(fetchManifest().then(function (data) {
    manifest = data;
  }).catch(function () {}));
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    (async function () {
      try {
        manifest = await fetchManifest();
        manifestLoaded = true;
        await applyManifest(manifest);
      } catch (error) {
        // A transient network failure must NEVER wipe a working cache. Keep
        // serving what we already know and retry on the next boot; unknown URLs
        // simply fall through to the network.
        console.log('[Twake Chat] manifest refresh failed, keeping cached resources: ', error);
        if (!manifestLoaded) await loadInitialManifest();
      }
      await self.clients.claim();
    })()
  );
});

async function applyManifest(fresh) {
  const contentCache = await caches.open(CACHE_NAME);
  const manifestCache = await caches.open(MANIFEST);
  const storedResponse = await manifestCache.match('manifest');
  const old = storedResponse ? await storedResponse.json() : null;
  const oldResources = (old && old.resources) || {};

  // Evict every entry that no longer matches the deploy: the hash changed (same
  // URL, new bytes), the path disappeared, or it was never ours to serve.
  for (const request of await contentCache.keys()) {
    const key = resourceKey(request.url);
    if (key === null || fresh.resources[key] === undefined ||
        fresh.resources[key] !== oldResources[key]) {
      await contentCache.delete(request);
    }
  }

  // Precache CORE best-effort so the first controlled load is served from cache.
  // The fetch is cachebusted with the deployed MD5 (?v=<hash>): the URL is only
  // fresh right after the bytes changed, so a proxy that ignores no-cache/etag
  // can never seed the cache with stale bytes. This intentionally bypasses
  // HTTP-cache coalescing with the page's own plain-URL fetch, so a changed
  // core asset (e.g. main.dart.js) may be downloaded once by the SW and once by
  // an uncontrolled cold page load. The response is still keyed under the plain
  // `url`, so cache keys, eviction and manifest lookups are unaffected.
  await Promise.allSettled(fresh.core.map(function (url) {
    if (fresh.resources[url] === undefined) return Promise.resolve();
    return contentCache.match(url).then(function (hit) {
      if (hit) return;
      return fetch(withBust(url, fresh.resources[url])).then(function (response) {
        if (response && response.ok) return contentCache.put(url, response);
      }).catch(function (error) {
        console.log('[Twake Chat] core precache miss: ' + url, error);
      });
    });
  }));

  await manifestCache.put('manifest', new Response(JSON.stringify(fresh)));
}

self.addEventListener('fetch', function (event) {
  if (event.request.method !== 'GET') return;
  const key = resourceKey(event.request.url);
  if (key === null) return; // outside our scope (e.g. cross-origin fonts)

  event.respondWith(
    (manifestLoaded ? Promise.resolve(manifest) : loadInitialManifest()).then(
      function (current) {
        // config.json, version.json and sw-manifest.json are deliberately absent
        // from resources (deploy-injected / version source), so they always hit
        // the network — nginx serves them Cache-Control: no-store.
        if (current.resources[key] === undefined) return fetch(event.request);

        // Serving index.html from cache would hide a deploy.
        if (key === '/') return onlineFirst(event.request);

        return serveFromCache(event);
      }
    )
  );
});

function serveFromCache(event) {
  return caches.open(CACHE_NAME).then(function (cache) {
    return cache.match(event.request).then(function (response) {
      return (
        response ||
        fetch(event.request).then(function (fetched) {
          if (fetched && fetched.ok) cache.put(event.request, fetched.clone());
          return fetched;
        })
      );
    });
  });
}

function onlineFirst(request) {
  return (
    fetch(request)
      .then(function (response) {
        // An error page must not become the cached shell: it would then be what
        // the offline fallback below serves. Return it, but keep it out.
        if (!response || !response.ok) return response;
        return caches.open(CACHE_NAME).then(function (cache) {
          return cache.put(request, response.clone()).then(function () {
            return response;
          });
        });
      })
      .catch(function (error) {
        // The shell is precached under index.html, so a root navigation misses
        // until an online load has stored '/' as well. Fall back to the shell,
        // or a first offline start would fail with the page already cached.
        return caches.open(CACHE_NAME).then(function (cache) {
          return cache
            .match(request)
            .then(function (response) {
              return response || cache.match('index.html');
            })
            .then(function (response) {
              if (response != null) return response;
              throw error;
            });
        });
      })
  );
}

self.addEventListener('push', function (event) {
  var data = {};
  try {
    data = event.data ? event.data.json() : {};
  } catch (e) {
    data = {};
  }
  // event_id_only: Sygnal flattens the payload, so we get { event_id, room_id,
  // counts, ... } plus the pusher's default_payload merged in at top level.
  // title/body come from default_payload — generic, app-localized strings set
  // at registration in the account language (NOT message content). Fall back to
  // English constants if absent (e.g. a pre-default_payload pusher).
  var n = data.notification || data || {};
  var roomId = n.room_id || '';
  var eventId = n.event_id || '';
  var title = n.title || 'Twake Chat';
  var body = n.body || 'New message';

  // The SW is the single notification owner on web (foreground + background).
  // Always show; the event_id tag dedupes repeats/retries of the same event.
  event.waitUntil(
    self.registration.showNotification(title, {
      body: body,
      icon: 'icons/Icon-192.png',
      badge: 'icons/Icon-192.png',
      tag: eventId || roomId || 'twake-message',
      renotify: true,
      data: { roomId: roomId, eventId: eventId },
    })
  );
});

self.addEventListener('pushsubscriptionchange', function (event) {
  // Endpoint rotated (expiry/reset). Re-subscribe so pushes keep arriving;
  // the Matrix pusher is re-synced by setupWebPush on the next app open
  // (it drops the stale pusher). applicationServerKey accepts the base64url
  // VAPID string directly.
  event.waitUntil(
    fetch('config.json')
      .then(function (r) { return r.json(); })
      .then(function (cfg) {
        if (!cfg || !cfg.vapid_public_key) return;
        return self.registration.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey: cfg.vapid_public_key,
        });
      })
      .catch(function (error) {
        console.log('[Twake Chat] pushsubscriptionchange re-subscribe failed: ', error);
      })
  );
});

self.addEventListener('notificationclick', function (event) {
  event.notification.close();
  var roomId = (event.notification.data || {}).roomId || '';
  var target = roomId ? '/#/rooms/' + roomId : '/';

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then(function (clientList) {
        for (var i = 0; i < clientList.length; i++) {
          var client = clientList[i];
          if ('focus' in client) {
            if (roomId && 'navigate' in client) client.navigate(target);
            return client.focus();
          }
        }
        if (self.clients.openWindow) return self.clients.openWindow(target);
      })
  );
});