/* Twake Chat — service worker: Web Push (RFC 8030) + precache.
 *
 * Pusher is event_id_only (same privacy contract as mobile): the push carries
 * NO message content — only event_id/room_id. The SW shows a generic
 * notification; the app fetches the content when the user clicks it. Sygnal's
 * events_only flag suppresses content-less count-clear pushes, so every push
 * maps to a real event (satisfies userVisibleOnly).
 *
 * A scope can only be controlled by a single service worker, so push and
 * precache share this file. Do not add a second registration under /web/: it
 * would silently replace this one.
 *
 * Precache manifest: generated by scripts/generate-sw-manifest.sh into
 * build/web/assets/sw-manifest.json. Flutter does not content-hash its output
 * filenames, so the manifest maps every scope-relative path to the MD5 of the
 * bytes that were actually deployed. The worker fetches it fresh at install,
 * at activate, and at the start of every root navigation (nginx serves it with
 * `Cache-Control: no-store`, and we also pass {cache:'no-store'} so the browser
 * HTTP cache can never hide a deploy) and evicts exactly the entries whose hash
 * changed. Refreshing on navigation is what lets an asset-only deploy — one
 * that leaves this file byte-identical, so the browser never reinstalls it —
 * still be picked up on the next reload. The worker itself is
 * version-independent: a deploy that only changes assets never reinstalls it.
 *
 * Since the manifest is fetched at runtime, this file is never built — keep it
 * as authored.
 *
 * ponytail: no JS test harness in this Flutter repo.
 */

'use strict';

// Reloaded from the network at the start of every boot. Sources of truth:
//   resources: { 'main.dart.js': 'md5', '/': '<index.html md5>', ... }
//   core:      ['main.dart.js', ...]  (subset of resources, precached eagerly)
// config.json, version.json and the manifest itself are deliberately absent:
// they are deploy-injected or carry the version, nginx serves them with
// 'Cache-Control: no-store', and we never intercept them.
const MANIFEST_URL = 'assets/sw-manifest.json';
const CACHE_NAME = 'twake-chat-cache';
const MANIFEST = 'twake-chat-manifest';

let manifest = { core: [], resources: {} };
let manifestLoaded = false;

// Keys in manifest.resources are scope-relative: the app is deployed under
// /web/, not at the origin root.
function resourceKey(url) {
  const scope = self.registration.scope;
  if (!url.startsWith(scope)) return null;
  const key = url.substring(scope.length);
  return key === '' ? '/' : key;
}

// Cachebuster for the SW's own asset fetches: appends the manifest MD5 as a
// GET param, so the URL is unique to the bytes actually deployed. A misbehaving
// middle layer that ignores `Cache-Control: no-cache` can never hand the fresh
// precache stale bytes pinned to the plain URL.
function withBust(url, hash) {
  const sep = url.includes('?') ? '&' : '?';
  return url + sep + 'v=' + hash;
}

// A manifest is usable only if it carries an object of resources and a core
// array. Split into single-branch checks to keep the conditional simple.
function isValidManifest(data) {
  if (!data) return false;
  if (typeof data.resources !== 'object') return false;
  return Array.isArray(data.core);
}

function fetchManifest() {
  return fetch(MANIFEST_URL, { cache: 'no-store' })
    .then(function (response) {
      if (!response.ok) throw new Error('manifest HTTP ' + response.status);
      return response.json();
    })
    .then(function (data) {
      if (!isValidManifest(data)) throw new Error('malformed manifest');
      return data;
    });
}

function loadStoredManifest() {
  return caches.open(MANIFEST).then(function (cache) {
    return cache.match('manifest').then(function (response) {
      return response ? response.json() : null;
    });
  });
}

function storedHasResources(stored) {
  if (!stored) return false;
  if (!stored.resources) return false;
  return Object.keys(stored.resources).length > 0;
}

// Before activation completes, the fetch handler may run with an empty in-memory
// manifest. Load the stored one once so a reload right after a worker restart is
// still served from cache. Falls back to the network when there is nothing yet.
async function loadInitialManifest() {
  try {
    const stored = await loadStoredManifest();
    if (storedHasResources(stored)) {
      manifest = stored;
    }
  } catch (error) {
    // A corrupt stored manifest must not break startup: serve from an empty
    // manifest (network) rather than reject every fetch.
    console.log('[Twake Chat] stored manifest unreadable, starting empty: ', error);
  }
  manifestLoaded = true;
  return manifest;
}

// True when the stored manifest no longer describes the same deploy.
function manifestChanged(stored, fresh) {
  if (!stored) return true;
  return JSON.stringify(stored.resources) !== JSON.stringify(fresh.resources);
}

// Fetch the deployed manifest and apply it if it moved, without ever letting a
// transient network failure wipe a working cache. Safe to call on every root
// navigation: unchanged deploys cost one small no-store request and no eviction.
async function doRefreshManifest() {
  let fresh;
  try {
    fresh = await fetchManifest();
  } catch (error) {
    // Keep serving what we already know and retry on the next navigation;
    // unknown URLs simply fall through to the network.
    console.log('[Twake Chat] manifest refresh failed, keeping cached resources: ', error);
    if (!manifestLoaded) await loadInitialManifest();
    return;
  }

  try {
    const stored = await loadStoredManifest();
    if (manifestChanged(stored, fresh)) await applyManifest(fresh);
    // Publish only once the cache matches the fresh manifest (or when nothing
    // had to change), so a failed eviction keeps the previous coherent pair.
    manifest = fresh;
    manifestLoaded = true;
  } catch (error) {
    // A failed cache update (QuotaExceededError, corrupt stored manifest, ...)
    // must NEVER break navigation: keep the previous manifest and serve on.
    console.log('[Twake Chat] manifest apply failed, keeping previous manifest: ', error);
    if (!manifestLoaded) await loadInitialManifest();
  }
}

// Concurrent navigations must not run applyManifest twice: coalesce them onto a
// single in-flight refresh.
let refreshInFlight = null;

function refreshManifest() {
  if (!refreshInFlight) {
    refreshInFlight = doRefreshManifest().finally(function () {
      refreshInFlight = null;
    });
  }
  return refreshInFlight;
}

self.addEventListener('install', function (event) {
  self.skipWaiting();
  // Best-effort warm-up so the fetch handler can serve immediately after
  // activation. A failure here is fine: activation retries and both paths fall
  // back to the network.
  event.waitUntil(fetchManifest().then(function (data) {
    manifest = data;
  }).catch(function () {}));
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    (async function () {
      await refreshManifest();
      await self.clients.claim();
    })()
  );
});

// Does this cached key still match the deploy? True when it is outside our
// scope, when the path disappeared, or when its hash changed.
function isStale(key, fresh, oldResources) {
  if (key === null) return true;
  if (fresh.resources[key] === undefined) return true;
  return fresh.resources[key] !== oldResources[key];
}

// A stale entry we must not delete: one we already refreshed in place, or an
// unreplaced core entry (serving slightly old bytes offline beats deleting the
// asset). Removed paths and non-core entries are safe to drop.
function shouldPreserveStale(key, fresh, staged) {
  if (staged.has(key)) return true;
  if (fresh.resources[key] === undefined) return false;
  return fresh.core.indexOf(key) >= 0;
}

// Fetch fresh core bytes (cachebusted with the deployed MD5) WITHOUT touching
// the cache yet, so a transient failure can never leave a core asset deleted and
// no replacement. Unchanged core already holds the right bytes. Returns a
// Map<url, Response> of the entries ready to install.
async function stageCore(contentCache, fresh, oldResources) {
  const staged = new Map();
  await Promise.all(fresh.core.map(async function (url) {
    const hash = fresh.resources[url];
    if (hash === undefined) return;
    if (oldResources[url] === hash && await contentCache.match(url)) return;
    try {
      const response = await fetch(withBust(url, hash));
      if (response && response.ok) staged.set(url, response);
    } catch (error) {
      console.log('[Twake Chat] core precache miss: ' + url, error);
    }
  }));
  return staged;
}

// Evict every entry that no longer matches the deploy: the hash changed (same
// URL, new bytes), the path disappeared, or it was never ours to serve.
async function evictStale(contentCache, fresh, oldResources, staged) {
  for (const request of await contentCache.keys()) {
    const key = resourceKey(request.url);
    if (!isStale(key, fresh, oldResources)) continue;
    if (key !== null && shouldPreserveStale(key, fresh, staged)) continue;
    await contentCache.delete(request);
  }
}

async function applyManifest(fresh) {
  const contentCache = await caches.open(CACHE_NAME);
  const manifestCache = await caches.open(MANIFEST);
  const old = await loadStoredManifest();
  const oldResources = (old && old.resources) || {};

  // 1. Stage the new core bytes (the deployed MD5 busts the URL), nothing is
  //    mutated yet: a failed core fetch must not delete the working copy.
  const staged = await stageCore(contentCache, fresh, oldResources);

  // 2. Write the staged bytes BEFORE evicting. cache.put overwrites the plain
  //    URL key in place, so old entries are never deleted without a replacement:
  //    a quota error here aborts with the previous entries still present.
  for (const [url, response] of staged) {
    await contentCache.put(url, response);
  }

  // 3. Evict what no longer matches, preserving the entries refreshed in step 2
  //    and any unreplaced core entry.
  await evictStale(contentCache, fresh, oldResources, staged);

  // 4. Publish the manifest only once the cache is coherent, so a concurrent
  //    fetch never sees a half-applied deploy.
  await manifestCache.put('manifest', new Response(JSON.stringify(fresh)));
}

self.addEventListener('fetch', function (event) {
  if (event.request.method !== 'GET') return;
  const key = resourceKey(event.request.url);
  if (key === null) return; // outside our scope (e.g. cross-origin fonts)

  event.respondWith(handleFetch(event, key));
});

async function handleFetch(event, key) {
  // Root navigation: refresh the manifest BEFORE the page requests its assets,
  // so an asset-only deploy (unchanged push_sw.js, so no reinstall) is matched
  // against the current hashes on this very load instead of the next one.
  if (key === '/') {
    await refreshManifest();
    return onlineFirst(event.request);
  }

  const current = manifestLoaded ? manifest : await loadInitialManifest();
  // config.json, version.json and sw-manifest.json are deliberately absent
  // from resources (deploy-injected / version source), so they always hit
  // the network — nginx serves them Cache-Control: no-store.
  if (current.resources[key] === undefined) return fetch(event.request);
  return serveFromCache(event);
}

function serveFromCache(event) {
  return caches.open(CACHE_NAME).then(function (cache) {
    return cache.match(event.request).then(function (response) {
      if (response) return response;
      return fetch(event.request).then(function (fetched) {
        // Keep the write inside the fetch event's lifetime, or the worker may
        // be torn down before the non-core resource is actually cached.
        if (fetched && fetched.ok) {
          event.waitUntil(cache.put(event.request, fetched.clone()));
        }
        return fetched;
      });
    });
  });
}

function onlineFirst(request) {
  return (
    fetch(request)
      .then(function (response) {
        // An error page must not become the cached shell: it would then be what
        // the offline fallback below serves. Return it, but keep it out.
        if (!response || !response.ok) return response;
        return caches.open(CACHE_NAME).then(function (cache) {
          return cache.put(request, response.clone()).then(function () {
            return response;
          });
        });
      })
      .catch(function (error) {
        // The shell is precached under index.html, so a root navigation misses
        // until an online load has stored '/' as well. Fall back to the shell,
        // or a first offline start would fail with the page already cached.
        return caches.open(CACHE_NAME).then(function (cache) {
          return cache
            .match(request)
            .then(function (response) {
              return response || cache.match('index.html');
            })
            .then(function (response) {
              if (response != null) return response;
              throw error;
            });
        });
      })
  );
}

self.addEventListener('push', function (event) {
  var data = {};
  try {
    data = event.data ? event.data.json() : {};
  } catch (e) {
    data = {};
  }
  // event_id_only: Sygnal flattens the payload, so we get { event_id, room_id,
  // counts, ... } plus the pusher's default_payload merged in at top level.
  // title/body come from default_payload — generic, app-localized strings set
  // at registration in the account language (NOT message content). Fall back to
  // English constants if absent (e.g. a pre-default_payload pusher).
  var n = data.notification || data || {};
  var roomId = n.room_id || '';
  var eventId = n.event_id || '';
  var title = n.title || 'Twake Chat';
  var body = n.body || 'New message';

  // The SW is the single notification owner on web (foreground + background).
  // Always show; the event_id tag dedupes repeats/retries of the same event.
  event.waitUntil(
    self.registration.showNotification(title, {
      body: body,
      icon: 'icons/Icon-192.png',
      badge: 'icons/Icon-192.png',
      tag: eventId || roomId || 'twake-message',
      renotify: true,
      data: { roomId: roomId, eventId: eventId },
    })
  );
});

self.addEventListener('pushsubscriptionchange', function (event) {
  // Endpoint rotated (expiry/reset). Re-subscribe so pushes keep arriving;
  // the Matrix pusher is re-synced by setupWebPush on the next app open
  // (it drops the stale pusher). applicationServerKey accepts the base64url
  // VAPID string directly.
  event.waitUntil(
    fetch('config.json')
      .then(function (r) { return r.json(); })
      .then(function (cfg) {
        if (!cfg || !cfg.vapid_public_key) return;
        return self.registration.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey: cfg.vapid_public_key,
        });
      })
      .catch(function (error) {
        console.log('[Twake Chat] pushsubscriptionchange re-subscribe failed: ', error);
      })
  );
});

self.addEventListener('notificationclick', function (event) {
  event.notification.close();
  var roomId = (event.notification.data || {}).roomId || '';
  var target = roomId ? '/#/rooms/' + roomId : '/';

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then(function (clientList) {
        for (var i = 0; i < clientList.length; i++) {
          var client = clientList[i];
          if ('focus' in client) {
            if (roomId && 'navigate' in client) client.navigate(target);
            return client.focus();
          }
        }
        if (self.clients.openWindow) return self.clients.openWindow(target);
      })
  );
});