# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane
default_platform(:android)

platform :android do
  lane :set_build_code_internal do
    versions = google_play_track_version_codes(
      track: "internal",
      json_key: "./keys.json"
    )
    last_version = versions[0].to_i
    version_name = last_git_tag.gsub("v", "")
    Dir.chdir("../..") do
      re = /version:\s([0-9]*\.[0-9]*\.[0-9]*)\+([0-9]*)/i
      config = File.read("./pubspec.yaml")
      match = config.match(re)
      current_version_code = match ? match[2].to_i : 0

      # Use the maximum of: version code from Google Play (internal track) and current pubspec.yaml
      effective_last_version = [last_version, current_version_code].max
      new_version_code = effective_last_version + 1

      subst = "version: #{version_name}+#{new_version_code}"
      result = config.gsub(re, subst)

      File.open("./pubspec.yaml", 'w') { |file| file.write(result) }
    end
  end

  lane :deploy_internal_test do
    track = "internal"
    upload_to_play_store(track: track,
                         aab: '../build/app/outputs/bundle/release/app-release.aab',
                         release_status: "completed")
  end

  lane :deploy_candidate do
    upload_to_play_store(track: 'internal', track_promote_to: "beta", deactivate_on_promote: false, skip_upload_changelogs: true)
  end

  lane :deploy_release do
    upload_to_play_store(track: 'beta', track_promote_to: "production", deactivate_on_promote: false, skip_upload_changelogs: true)
  end
end
